In [23]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Load your dataset
# Replace 'your_dataset.csv' with your actual dataset file
data = pd.read_csv('/content/synthetic_sports_team_fan_loyalty_data.csv')
data



age  income  years_as_fan  number_of_games_attended  \
0     56   30287            22                        32   
1     46   59387            20                        17   
2     32   33512            28                        48   
3     60   26342            25                        27   
4     25   88076            11                        46   
..   ...     ...           ...                       ...   
995   22   31276            13                        30   
996   40  104530             4                        13   
997   27   48499            23                        33   
998   61  113576            17                        17   
999   19  107495            23                        33   

     team_performance_rating  engagement_with_team  loyalty  
0                   7.495494                     2        1  
1                   3.443923                     1        0  
2                   4.622020                     0        0  
3                   1.924734                     1        0  
4                   2.701356                     2        0  
..                       ...                   ...      ...  
995                 4.624982                     1        0  
996                 9.732118                     1        0  
997                 9.390905                     0        0  
998                 7.674424                     2        1  
999                 3.514743                     0        0  

[1000 rows x 7 columns]

In [31]:



X = data.drop(columns=['loyalty'])
y = data['loyalty']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

# Create a logistic regression model
model = LogisticRegression(penalty='l1', solver='liblinear')

# Fit the model to the training data
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)
y_pred


array([1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [32]:
y_pred1 = model.predict(np.array([61,113576,17,17,7.674424,2	]).reshape(1,-1)) # Reshape the 1D array to a 2D array with one row and six columns
y_pred1

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1])

In [33]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy:.2f}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)

Accuracy: 0.81
Confusion Matrix:
[[131  12]
 [ 27  30]]
Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.92      0.87       143
           1       0.71      0.53      0.61        57

    accuracy                           0.81       200
   macro avg       0.77      0.72      0.74       200
weighted avg       0.80      0.81      0.80       200



In [35]:
cv_scores = cross_val_score(model, X, y, cv=5, scoring='accuracy')
cv_scores

array([0.84 , 0.815, 0.815, 0.845, 0.855])